# Generated by Django 3.1.7 on 2021-03-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arXiv', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('journal', models.CharField(max_length=25)),
                ('volume', models.CharField(max_length=10)),
                ('page', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=30)),
                ('collaboration', models.CharField(max_length=30)),
                ('doi', models.CharField(max_length=30)),
                ('bibtex', models.TextField()),
                ('citation_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
