# Generated by Django 3.1.7 on 2021-03-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='arXiv',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='bibtex',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='collaboration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='page',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
